# Generated by Django 4.2.5 on 2023-09-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('property_cost', models.CharField(max_length=200)),
                ('property_type', models.CharField(max_length=200)),
                ('property_locality', models.CharField(max_length=1000)),
                ('property_city', models.CharField(max_length=100)),
                ('property_area', models.CharField(max_length=1000)),
            ],
        ),
    ]
