# Generated by Django 4.2.5 on 2023-09-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSScraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCronjobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
    ]
